name: emready_env
channels:
  - defaults
  - nvidia
  - pytorch
dependencies:
  - python=3.9
  - pip=23.3
  - pytorch==2.0.0
  - torchvision==0.15.0
  - torchaudio==2.0.0
  - pytorch-cuda==11.7
  - mkl==2020.0
  - numba==0.60.0
  - pip:
    - biopython==1.81
    - einops==0.6.1
    - mrcfile==1.3.0
    - numpy==1.24.2
    - timm==0.9.2
    - tqdm==4.60.0
